### ISSUE TITLE
Object.freeze() failing with TypedArray

### ISSUE THREAD

**Issue by CharCake** [morganherlocker/cubic-spline#12]
Having the performance update when updating from cubic-spline 3.0.1 to 3.0.2 (or 3.0.3) "speed up curve initialization" caused a problem when using NGRX (https://ngrx.io/) that uses Object.freeze() to prevent data mutation. I have an object that has spline in its property in my store.

The update adds Float64Array which can not be frozen based on an answer here https://stackoverflow.com/a/41024384

"Typed buffer could refer a slice of the original buffer, and several typed buffers could refer the same slice of the original buffer." "freezing typed buffer could not protect original data from being changed"

The error I get is "Uncaught TypeError: Cannot freeze array buffer views with elements"

Downgrading to 3.0.1 fixes the problem, but using further updates of cubic-spline with the Float64Array and the setup of having spline at NGRX store do not seem to be possible.

**Comment by srmagura** [comment]
I don't know anything about NgRx, but it may be better to only store serializable objects in the store (this is the what you are supposed to do for Redux, a similar library for React). This means you should not store a class instance (like `Spline`) in the store.

**Comment by morganherlocker** [comment]
Yep, agree with @srmagura here.
