### ISSUE TITLE
Is there a way to get Bezier points from this code?

### ISSUE THREAD

**Issue by danzen** [morganherlocker/cubic-spline#13]
Hi Morgan - if I have 10 points for example, can I get Bezier points (two handles and the next point) from this code?  If not, would you have a JS recommendation to be able to do this?  Thanks.

**Comment by danzen** [comment]
Hmmm... just found this http://blog.ivank.net/interpolation-with-cubic-splines.html and perhaps in the comments it says these are different things.  Still hunting for a Bezier point solution been at it for an hour or so - for the third time in a week or two.  Sigh.  Any suggestions from one who knows more about this would certainly be welcome. Cheers.

**Comment by srmagura** [comment]
As you suspected, Bezier curves and cubic splines are different (though possibly related on a mathematical level). This library will not give you the Bezier points for a dataset.
