### ISSUE TITLE
Getting NaN

### ISSUE THREAD

**Issue by jmbldwn** [morganherlocker/cubic-spline#2]
My data looks fine, but getting NaN out of the interpolation.

I have 48 points.  Too much?

Here's my data:

{ x: 
   [ 0,
     105,
     210,
     315,
     420,
     525,
     630,
     735,
     840,
     945,
     1050,
     1155,
     1260,
     1365,
     1470,
     1575,
     1680,
     1785,
     1890,
     1995,
     2100,
     2205,
     2310,
     2415,
     2520,
     2625,
     2730,
     2835,
     2940,
     3045,
     3150,
     3255,
     3360,
     3465,
     3570,
     3675,
     3780,
     3885,
     3990,
     4095,
     3990,
     4011,
     4032,
     4053,
     4074,
     4095 ],
  y: 
   [ 105.036940831,
     104.891700408,
     104.82317453,
     104.8619396,
     105.004838143,
     105.231628571,
     105.555757057,
     105.992371744,
     106.655118774,
     107.575233042,
     108.791316294,
     110.550493478,
     113.14888371,
     116.908401909,
     122.605462981,
     131.326998055,
     143.984127618,
     161.122377331,
     182.405851718,
     206.460142114,
     231.843804211,
     256.790869497,
     279.855799584,
     299.94115997,
     316.613522732,
     330.002984675,
     340.32953856,
     348.101901374,
     353.798831738,
     357.950338381,
     360.861892074,
     362.935810709,
     364.487517947,
     365.44702043,
     366.217323277,
     366.717293087,
     367.101728848,
     367.41496388,
     367.53610901,
     367.765018047,
     367.48578423,
     367.519356373,
     367.469896218,
     367.499185212,
     367.46981998,
     367.471566401 ] }

**Comment by saumyaj92** [comment]
Is there any solution to this? I am getting NaN too.

**Comment by saisankargochhayat** [comment]
Its because extrapolation is not accounted for , can you please look into it ?

**Comment by TeenaPI** [comment]
I am also getting the same error. Any solution for this issue? How to consider extrapolation as mentioned in comments??

**Comment by RexHuang** [comment]
check my fix:
https://github.com/morganherlocker/cubic-spline/pull/5

**Comment by morganherlocker** [comment]
@RexHuang Thanks for the fix! I have published your changes under a new major version, v3.0.0. I probably could have used a patch, but I wanted to avoid any surprises if folks were counting on the old behavior, since its worked this way for 5 years now. If anyone sees similar behavior in v3, please open a new issue, and I'll take a look.

**Comment by RexHuang** [comment]
great！
