### ISSUE TITLE
some points not on curve line

### ISSUE THREAD

**Issue by DustarMao** [morganherlocker/cubic-spline#8]
```js
const y = new CubicSpline([0, .2, .5, 1], [0, .35, .5, 1]).at(.5)
console.log(y) // 0.12748344370860887 != 0.5
```

version: 3.0.2

**Comment by wojtus7** [comment]
Hi @DustarMao 
I believe I resolved this issue here https://github.com/morganherlocker/cubic-spline/pull/9.
Can you check out if this change fix the problem for you?

**Comment by morganherlocker** [comment]
The patch from @wojtus7 has been published. Please try upgrading and reopen this issue if the problem persists @DustarMao.
